Repository ibexa/user, pull requests merged in 2022-06, with the labels that each got.

#40 IBX-2829: Added option to configure fields for register form
  src/bundle/DependencyInjection/Configuration/Parser/UserRegistration.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/lib/Form/Type/Invitation/SiteAccessChoiceType.php
  src/lib/Form/Type/UserRegisterType.php
  src/lib/Permission/UserPermissionsLimitationType.php
  tests/lib/Permission/UserPermissionsLimitationTypeTest.php
Labels: Doc needed, QA approved

#42 IBX-2977: Added API for invitation refreshing
  composer.json
  phpunit.xml
  src/contracts/Invitation/InvitationService.php
  src/contracts/Invitation/Persistence/Gateway.php
  src/contracts/Invitation/Persistence/Handler.php
  src/contracts/Invitation/Persistence/InvitationUpdateStruct.php
  src/lib/Invitation/InvitationService.php
  src/lib/Invitation/Persistence/DoctrineGateway.php
  src/lib/Invitation/Persistence/Handler.php
  tests/integration/Invitation/InvitationServiceTest.php
Labels: Doc needed, Rebase required

#43 IBX-3070: User thumbnail should not be rendered with border and other minor bugs
  src/bundle/Controller/DefaultProfileImageController.php
  src/bundle/Resources/views/profile_image/initials.svg.twig
Labels: QA approved
