Repository ibexa/user, pull requests merged in 2024-01, with the labels that each got.

#64 IBX-7037: Added check if user has permission to change password
  src/bundle/Controller/UserSettingsController.php
Labels: Bug, QA approved

#70 IBX-7369, IBX-7371: Added UserRegister and UserPasswordReset notification
  composer.json
  src/bundle/Controller/PasswordResetController.php
  src/contracts/Notification/UserAwareNotificationInterface.php
  src/contracts/Notification/UserPasswordReset.php
  src/contracts/Notification/UserRegister.php
  src/lib/Form/Processor/UserRegisterFormProcessor.php
  tests/integration/IbexaTestKernel.php
Labels: Feature, Ready for review

#67 IBX-7119, IBX-7171, IBX-7123: Corrected Headers inconsistency in Account settings
  src/bundle/Controller/UserSettingsController.php
  src/bundle/Resources/translations/ibexa_user_settings.en.xliff
  src/lib/UserSetting/Group/EditContentGroup.php
Labels: Bug, Ready for QA
